### ISSUE TITLE
dbinit and not db-init inside https://raw.githubusercontent.com/devops-with-openshift/liquibase- example/master/dbinit-deployment-config.json

### ISSUE THREAD

**Issue by dwojciec** [devops-with-openshift/liquibase-example#1]
During the oc deploy dbinit --latest (I replaced by oc rollout latest dc/dbinit in OCP 3.5) I received this error 
oc rollout latest dbinit
Error from server (BadRequest): cannot trigger a deployment for "dbinit" because it contains unresolved images

But I discovered inside https://raw.githubusercontent.com/devops-with-openshift/liquibase- example/master/dbinit-deployment-config.json
image is db-init and not dbinit 

Second remark:  --value has been deprecated, Use -p, --param instead 

oc process -f https://raw.githubusercontent.com/eformat/liquibase-example/master/dbinit-deployment-config.json -v="IMAGE_STREAM=$(oc get is/dbinit | grep -v DOCK| awk '{print $2}')" | oc create -f -
Flag --value has been deprecated, Use -p, --param instead.

Fantastic book !!!

**Comment by tomwu-tw** [comment]
Same error found, @dwojciec good findings!

**Comment by tomqwu** [comment]
https://github.com/devops-with-openshift/liquibase-example/pull/2

**Comment by MrFishFinger** [comment]
i ran into the same issue, and used the branch from @tomqwu to resolve.

@devops-with-openshift - can you please merge the PR?

in the meantime, i worked around this issue by using these steps:

```oc create -f https://raw.githubusercontent.com/eformat/liquibase-example/master/dbinit-data-pvc.yaml
oc new-app https://github.com/eformat/liquibase-example.git --name=dbinit --strategy=docker
oc delete dc/dbinit
oc process -f https://raw.githubusercontent.com/tomqwu/liquibase-example/master/dbinit-deployment-config.json -p "IMAGE_STREAM=$(oc get is/dbinit | grep -v DOCK| awk '{print $2}')" | oc create -f -
oc rollout latest dc/dbinit```

(note that the json URL is for the branch from @tomqwu )

**Comment by devops-with-openshift** [comment]
Fixed with Merge. Thankyou.
